# Generated by Django 2.1.2 on 2018-11-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nephrosis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
