# Generated by Django 2.1.2 on 2018-11-08 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nephrosis', '0003_auto_20181108_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_time', models.DateTimeField()),
                ('inspection_item', models.CharField(max_length=10)),
                ('inspecgtion_value', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nephrosis.Patient')),
            ],
        ),
    ]
