# Generated by Django 2.1.2 on 2018-11-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nephrosis', '0004_inspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspection_time',
            field=models.DateField(),
        ),
    ]
