# Generated by Django 2.1.2 on 2018-11-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nephrosis', '0005_auto_20181108_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nephs_proba',
            field=models.FloatField(default=0.92),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='nonnephs_proba',
            field=models.FloatField(default=0.08),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='user_prediction',
            field=models.BooleanField(),
        ),
    ]
