# Generated by Django 2.1.2 on 2018-11-12 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nephrosis', '0006_auto_20181108_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cond_exp', models.CharField(max_length=20)),
                ('contribution', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nephrosis.Patient')),
            ],
        ),
    ]
