# Generated by Django 2.1.2 on 2018-11-14 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nephrosis', '0007_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nephrosis.Patient'),
        ),
        migrations.AlterField(
            model_name='result',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nephrosis.User'),
        ),
    ]
