# Generated by Django 2.1.2 on 2018-11-16 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nephrosis', '0008_auto_20181114_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='inspecgtion_value',
            new_name='inspection_value',
        ),
    ]
