# Generated by Django 2.1.2 on 2018-11-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nephrosis', '0009_auto_20181116_0714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='inspection_time',
            new_name='inspection_date',
        ),
    ]
