# Generated by Django 2.1.2 on 2018-11-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nephrosis', '0010_auto_20181116_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspection_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
